// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syzkbimsyjkfxukxsadl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5emtiaW1zeWprZnh1a3hzYWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDM1NDgsImV4cCI6MjA3MDMxOTU0OH0.5nkuew_5xcmVTfpc2JdfmN-s_4JX5pu9wswBYNMVN2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});